Settings:
  DP-UniversalCore:
    # 해당 플러그인의 업데이트 체크 여부
    update-check: true
    # 해당 플러그인의 업데이트 체크 주기 (초단위)
    update-check-interval: 3600
    # https://bstats.org/ 해당 사이트에 플러그인 사용 통계를 전송합니다.
    # 해당 기능을 사용하신다면 플러그인 개발자를 구독한거나 다름없습니다!
    # 해당 사이트에서 지원하는 통계의 기능으로 저는 얼마나 많은 서버에서 해당 플러그인을 사용하는지 알 수 있습니다. XD
    use-metrics: true

  DP-VirtualStorage:
    update-check: true
    update-check-interval: 3600
    use-metrics: true

  DP-LegendaryCash:
    update-check: true
    update-check-interval: 3600
    use-metrics: true

  DP-SimplePrefix:
    update-check: true
    update-check-interval: 3600
    use-metrics: true
  DP-ItemEditor:
    update-check: true
    update-check-interval: 3600
    use-metrics: true