name: DP-UniversalCore
version: 1.0.0.12
main: com.darksoldier1404.duc.UniversalCore
api-version: 1.17
authors: [ DEAD_POOLIO_ ]
softdepend:
  - Essentials
  - PlaceholderAPI
  - ProtocolLib
  - DP-LegendaryCash
  - DP-VirtualStorage
