name: DP-UniversalCore
version: 1.0.6.164
main: com.darksoldier1404.duc.UniversalCore
api-version: 1.12
authors: [ DEAD_POOLIO_ ]
loadbefore:
  - Essentials
  - PlaceholderAPI
  - ProtocolLib
  - DP-LegendaryCash
  - DP-VirtualStorage
  - DP-SimplePrefix
commands:
  duc:
